service: colab-infra
frameworkVersion: "2"

custom:
  stage: ${opt:stage, 'staging'}
  region: sa-east-1
  DYNAMO_TABLE: ${self:service}-db
  appSync: ${file(./serverless_extend/appSync.yaml)}


provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:            
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.DYNAMO_TABLE}"

functions: 
  create:
    handler: functions/post.create
    environment:
      DYNAMO_TABLE_NAME: { "Ref": "DynamoTable"} # Alterado de !Ref DynamoTable para { "Ref": "DynamoTable"} apenas para resolver problema no linter
  get:
    handler: functions/post.get
    environment:
      DYNAMO_TABLE_NAME: { "Ref": "DynamoTable"} # Alterado de !Ref DynamoTable para { "Ref": "DynamoTable"} apenas para resolver problema no linter
#   postUpdate:
#     handler: functions/post.update
#     environment:
#       DYNAMO_TABLE_NAME: { "Ref": "DynamoTable"} # Alterado de !Ref DynamoTable para { "Ref": "DynamoTable"} apenas para resolver problema no linter
#   postDelete:
#     handler: functions/post.delete
#     environment:
#       DYNAMO_TABLE_NAME: { "Ref": "DynamoTable"} # Alterado de !Ref DynamoTable para { "Ref": "DynamoTable"} apenas para resolver problema no linter

resources:
  Resources:
    DynamoTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.DYNAMO_TABLE}

plugins:
  - serverless-appsync-plugin